version: '3.5'

x-db: &db_template
  image: mysql:5.7
  environment:
    - MYSQL_RANDOM_ROOT_PASSWORD=yes
    - MYSQL_DATABASE=isi_payment
    - MYSQL_PASSWORD=db_password
    - MYSQL_USER=isi_payment
  command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci]
  networks:
    - fixit

x-php-fpm: &php_fpm_template
  build: ./images/php-fpm
  networks:
    - fixit

x-nginx: &nginx_template
  image: nginx:1.17.1-alpine
  networks:
    - fixit

services:
  php-fpm:
    container_name: isi-payment_fpm
    <<: *php_fpm_template
    volumes:
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./config/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./config/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./isi-payment:/var/www/isi-payment
      - ./isi-payment/.composer/cache:/home/www-data/.composer/cache

  nginx:
    container_name: isi-payment_nginx
    <<: *nginx_template
    ports:
      - "${NGINX_PORT:-8080}:80"
    volumes:
      - ./isi-payment:/var/www/isi-payment
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf

  db:
    container_name: isi-payment_db
    <<: *db_template
    ports:
      - "3306:3306"
    volumes:
      - data-mysql:/var/lib/mysql

volumes:
  data-mysql:
    name: isi-payment_db

networks:
  fixit:
    name: fixit
